### ISSUE TITLE
Why isn't this available in NPM registry?

### ISSUE THREAD

**Issue by sarbogast** [jojoee/leo-profanity-typescript#7]
I really need a profanity filtering library that works in TypeScript. Tried to integrate bad-words, but I couldn't get it to work. Please publish.

**Comment by jojoee** [comment]
Ok, I'll do it tomorrow.

**Comment by jojoee** [comment]
The Typescript module is not working yet,
but you can use this as an alternative.

```javascript
import * as filter from 'leo-profanity'
console.log('list', filter.list())
console.log('clean', filter.clean('I have boob, etc.'))
```

**Comment by sarbogast** [comment]
But how can it work without a type definition?
